export const GET_ALL_CUSTOMER = "GET_ALL_CUSTOMER"
export const GET_CUSTOMER_BY_ID = "GET_CUSTOMER_BY_ID"
export const ADD_CUSTOMER = "ADD_CUSTOMER"
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER"
export const DELETE_CUSTOMER = "DELETE_CUSTOMER"

